### PR TITLE
Add support for GitHub avatars to replace Gravatar

### PR DESCRIPTION
**Pull request by tildehacker**
# Description

I don't have a Gravatar account (asks for a WordPress.com account...) so I added a way to use GitHub avatar on the main page instead of Gravatar.

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

# How Has This Been Tested?

I manually tested the different possible combinations in `_config.yml`.

- [x] `avatar_source: SOMETHING`
- [x] `avatar_source: gravatar`
- [x] `avatar_source: github` and no `github_username`
- [x] `avatar_source: github` and `github_username: NON_EXISTING`
- [x] `avatar_source: github` and `github_username: bitbrain`

# Checklist:

- [ ] Check if github_username really exists
- [x] Make `avatar_source: gravatar` the default (change becomes non-breaking)
- [x] Add documentation in `README.md`

### CODE REVIEW

**Comment by bitbrain** [comment]
@tildehacker I see various things are not checked - is this ready to go or are you still adding things?

**Comment by tildehacker** [comment]
> 
> 
> @tildehacker I see various things are not checked - is this ready to go or are you still adding things?

Hi, I converted this pull request to a draft.

**Comment by tildehacker** [comment]
I made some changes to make this branch non-breaking (gravatar is the default provider now). And I added the same code in `_config.yml` to `README.md` to showcase that using GitHub's avatar is possible too.

If the user sets a `github_username` that doesn't exist, the `alt` text will be shown like below (without any validation).

alt-text

**Comment by bitbrain** [comment]
Woah, this is really nice.

Thanks a lot for the hard work. ❤

**Pull request merged**
